# Session 3

### Assignment 1 Question

### Task 1:

1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [10]:
def divzero():
    try:
        val = 5/0
    except Exception as e:
        print(e)
    

In [11]:
divzero()

division by zero


2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [16]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

list_tot = [(sub+" "+verb+" "+obj) for sub in subjects for verb in verbs for obj in objects]

for line in list_tot:
    print(line)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2:

In [ ]:
1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [51]:
import numpy as np


def vander_matrix(ipv,N,increasing):
    if increasing is False:
        matx_output = np.array([x**(N-i-1) for x in ipv for i in range(N)]).reshape(ipv.size,N)
    elif increasing is True:
        matx_output = np.array([x**i for x in ipv for i in range(N)]).reshape(ipv.size,N)
    
    return matx_output

print("=================OUTPUT====================\n")

input_vector = np.array([2,3,4,5])
N=4

matx_output_dec = vander_matrix(input_vector,N,False)
matx_output_inc = vander_matrix(input_vector,N,True)

print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix :",N,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",matx_output_dec,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",matx_output_inc,"\n")

print("=============================================")

=================OUTPUT====================

The input array is: [2 3 4 5] 

Number of columns in output matrix : 4 

Vander matrix of the input array in decreasing order of powers:

 [[  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 

